web/views.py
from django.views.decorators.http import *
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from core import models
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
import re
from django.contrib.auth.decorators import login_required
from forms import EditCheckForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from tagging.models import Tag, TaggedItem

def home(request):
    return render(request, 'web/home.html', {} )

@login_required
def list(request, tag_selected=None):
    if not tag_selected:
        startSet = models.Check.objects
    else:
        startSet = TaggedItem.objects.get_by_model(models.Check, Tag.objects.get(name=tag_selected))
    checks_enabled = startSet.filter(enabled=True, owner=request.user).order_by('prefix', 'name').all()
    checks_disabled = startSet.filter(enabled=False, owner=request.user).order_by('prefix', 'name').all()
    notifications = models.NotificationReceiver.objects.filter(owner=request.user).all()
    tags = models.Check.tags.usage(filters={'owner': request.user, 'enabled': True})
        
        
    return render(request, 'web/list.html', {
        'checks_enabled' : checks_enabled,
        'checks_disabled' : checks_disabled,
        'notifications' : notifications,
        'tags': tags,
        'tag_selected': tag_selected,
        })

@login_required
def details(request, apikey):
    check = get_object_or_404(models.Check, apikey=apikey, owner=request.user)
    events = models.CheckEvent.objects.filter(source=check).order_by('-timestamp').all()
    if request.method == 'POST' and request.POST['action'] == 'remove':
        for e in events.all():
            e.delete()
        check.delete()
        return HttpResponseRedirect(reverse('web:list'))

    if request.method == "POST":
        form = EditCheckForm(request.user, request.POST, instance=check)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('web:details', kwargs={'apikey': apikey}))
    else:
        form = EditCheckForm(request.user, instance=check)

    paginator = Paginator(events, 20, orphans=5)
    page = request.GET.get('page')
    try:
        events = paginator.page(page)
    except PageNotAnInteger:
        events = paginator.page(1)
    except EmptyPage:
        events = paginator.page(paginator.num_pages)
        
    return render(request, 'web/details.html', {
        'check': check,
        'events': events,
        'form': form,
        })


@login_required
@require_http_methods(["POST"])
def toggle(request):
    check = get_object_or_404(models.Check, apikey=request.POST['apikey'], owner=request.user)
    check.enabled = not check.enabled
    check.save()
    return HttpResponseRedirect(reverse('web:list'))

@login_required
@require_http_methods(["POST"])
def check_add(request):
    if len(request.POST['name']) == 0:
        return HttpResponseRedirect(reverse('web:list'))        
    check = models.Check(owner=request.user, name=request.POST['name'])
    check.save()
    check.notifications = models.NotificationReceiver.objects.filter(owner=request.user).all()
    check.save()
    return HttpResponseRedirect(reverse('web:details', kwargs={'apikey': check.apikey}))

@login_required
@require_http_methods(["POST"])
def notification_remove(request):
    r = get_object_or_404(models.NotificationReceiver, id=request.POST['remove-notification'], owner=request.user)
    r.delete()
    return HttpResponseRedirect(reverse('web:list'))

@login_required
@require_http_methods(["POST"])
def notification_add(request):
    email = request.POST['email']
    if re.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$", email):
        r = models.NotificationReceiver(address = email, owner = request.user)
        r.send_confirmation_token(request)
        r.save()
    return HttpResponseRedirect(reverse('web:list'))

@login_required
def confirm_email(request, token):
    n = get_object_or_404(models.NotificationReceiver, owner=request.user, confirmation_token=token)
    n.confirmation_token = None
    n.save()
    return HttpResponseRedirect(reverse('web:list'))

web/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>totmann, a dead man's switch for cron jobs</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{% static "css/normalize.css" %}">
  <link rel="stylesheet" href="{% static "css/skeleton.css" %}">

  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="icon" type="image/png" href="{% static "images/favicon.png" %}">
  <style>
    .green {
    color: #494;
    }
    .red {
    color: #944;
    }
    .orange {
    color: #f90;
    }
    .gray {
    color: #ccc;
    }
    .linkbutton, .linkbutton:focus {
    background:none!important;
    border:none; 
    padding:0!important;
    color: #1EAEDB;
    cursor:pointer;
    text-decoration: underline;
    text-transform: none;
    font-family: inherit;
    font-size: inherit;
    font-weight: inherit;
    letter-spacing: inherit;
    
    }
    .linkbutton:hover {
    color: #0FA0CE;
    }
    .url {
    font-family: monospace;
    }

    #id_notifications {
    width: 50%;
    height: 100px;
    }

    .status-failed {
    color: #944;
    }
    .status-warning {
    color: #f90;
    }
    .status-started {
    color: #ccc;
    }
    .status-log {
    color: #ccc;
    }
    .status-finished {
    color: #494;
    }
    #watermark
    {
    position:relative;
    right: 13em;
    opacity:0.1;
    z-index:99;
    text-align: left;
    width: 10em;
    height: 0px;
    top: -2.6em;
    }
    #watermark a
    {
    display: block;
    color:black !important;
    text-decoration: none;
    font-size: 10em;
    transform: rotate(-90deg);
    direction: rtl;
    }
    .legal {
    color:#999;
    }
    .with-top-margin {
    margin-top: 10%;
    }
    .check-tag {
    border-radius: 4px;
    background-color: #ccc;
    padding: 0px 4px;
    margin-right: 3px;
    text-decoration: none;
    color: inherit;
    }
    .check-tag.active {
    background-color: #669;
    color: #ddd;
    }
    
  </style>
</head>
<body>
  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <div class="container">
    <div class="row">
      <div class="{% block width %}twelve columns{% endblock %} with-top-margin">
	<div id="watermark"><a href="{% url "home" %}">totmann</a></div>
	{% block extralinks %}{% endblock %}
	<h4>{% block title %}Totmann{% endblock %}.</h4>
	{% block content %}No content.{% endblock %}


	</div>
      {% block second_column %}{% endblock %}
    </div>
    {% if user.is_authenticated %}<div id="userfooter row">logged in as {{ user }}. <a href="{% url 'auth_logout' %}">log out.</a>{% endif %}
  </div>

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>
</html>